### ISSUE TITLE
Linux Port

### ISSUE THREAD

**Issue by butchcom** [PiMaker/MonikAI#13]
Is it possible to provide a Linux port of this application?

**Comment by supernegativep** [comment]
Have you tried it in wine yet?

**Comment by zchaudhry11** [comment]
A Linux port would be very cool, unfortunately, it would likely also be a great deal of work because MonikAI is built on top of .NET Framework which is tightly coupled to Windows.

.NET Core is available and it can be combined with some third party libraries and frameworks to get MonikAI on Linux but this would likely require a lot of additional work.

**Comment by butchcom** [comment]
I tried starting it with wine. I managed to start the .exe using a 32-bit prefix and dotnet46. Unfortunately it doesn't display anything, the last error being `wine: Call from 0x7bc51219 to unimplemented function MSVCR100_CLR0400.dll._initterm_e, aborting`. It seems to have to problem with PresentationFramework.

Does .NET Core implement the WPF libraries?

**Comment by zchaudhry11** [comment]
It doesn't support WPF and it's not on the roadmap either but there have been some frameworks that are looking to fill the gap such as https://github.com/AvaloniaUI/Avalonia

Everything is still really early alpha so I don't think it would be a straightforward process to rebuild MonikAI to be cross-platform.

**Comment by PiMaker** [comment]
If anyone wants to look into Wine/Mono/Whatever, feel free to, but for now I won't officially support a Linux or Mac port.
